### ISSUE TITLE
Make the website responsive. 

### ISSUE THREAD

**Issue by bodhish** [coronasafe/kerala_map#2]
It would pretty straight forward to use tailwind table so that it could mobile optimized.

You can copy tailwind table styling from volunteer.coronasafe.network

**Comment by saanuregh** [comment]
latest commit fixes for smaller devices but it bugs out in medium

**Comment by firofame** [comment]
Can we just highlight the row selected in the map instead of showing the details. It feels a bit clutter in mobile

**Comment by saanuregh** [comment]
@firofame what do u mean?

**Comment by firofame** [comment]
![IMG_20200327_140421](https://user-images.githubusercontent.com/11689383/77737397-e40e3200-7033-11ea-8206-7ec193800fba.jpg)

Isn't the data redundant? We can just give the selected district a different color

**Comment by saanuregh** [comment]
the above field only shows data of the selected district, districts on map are clickable

**Comment by firofame** [comment]
When we click a district on the map why don't we highlight the clicked district in the table.

**Comment by AzadNikarthil** [comment]
![image](https://user-images.githubusercontent.com/29298619/77811972-35fe9880-70c4-11ea-94a7-2fcc3710b548.png)

Information is not shown completely in the browser

**Comment by firofame** [comment]
@AzadNikarthil  Both sides have 7 category of data. What do you mean by "Information is not shown completely in the browser"

**Comment by saanuregh** [comment]
done
