### ISSUE TITLE
daily addition: Kerala Dashaboard

### ISSUE THREAD

**Issue by aparnacoronasafe** [coronasafe/kerala_map#35]
https://kerala.coronasafe.network/

The Kerala dashboard currently shows the daily increase in Percentage.

Kindly change that to the actual number so that the daily declared positives with the state and within various districts may be easily visible. 

@saanuregh

**Comment by saanuregh** [comment]
@aparnacoronasafe changed

**Comment by aparnacoronasafe** [comment]
Cannot see any change. Please confirm
